export interface Advisor {
  slug: string
  name: string
  title: string
  specialty: string
  bio: string
  credentials: string[]
  rating: number
  clients: number
  image: string
  quote: string
  email?: string
  phone?: string
  whatsapp?: string
}

export const advisors: Advisor[] = [
  {
    slug: 'assuredbydovanson',
    name: 'Dovanson Quah',
    title: 'Financial Services Director',
    specialty: 'Team Leadership & Comprehensive Financial Planning',
    bio: "I'm Dovanson Quah, the Financial Services Director leading this team of wonderful and amazing advisors. The teamwork and camaraderie forged through good times and bad ones have allowed this team to consistently outperform industry standards in providing financial planning advice. I wouldn't be where I am today if not for the hard work and dedication of each and every person in this agency. So don't read my story, read theirs. Together we strive to give our very best to every single one of our clients.",
    credentials: ['Financial Services Director', 'AIA Elite'],
    rating: 5.0,
    clients: 200,
    image: '/advisors/dovanson.jpg',
    quote: '"Mission before Commission."',
    email: 'dovanson@aia.com.sg',
    phone: '+65 9385 0207',
    whatsapp: 'https://api.whatsapp.com/send?phone=6593850207',
  },
  {
    slug: 'assuredbyyvonne',
    name: 'Yvonne Lim',
    title: 'Financial Services Consultant',
    specialty: 'Long-Term Financial Planning & Career Mentorship',
    bio: "A job that recognises your effort? A job that allows you to plan your own schedule? I saw this when I first joined at 22 and I knew it would become a reality, only if I put my mind into it. The initial stages of failures and rejections were enough to turn many away. However, what I chose to see was \"I have to be better and rise up to the standards for people to entrust their lives with me\". With this, it accompanied me through 7 years of my career, to constantly learn and strive to provide valued advices to my clients. Everyone needs a mentor or a role model. Thankfully at Spartans Advisors, I have always been given opportunities to learn from the best; successful individuals who share and guide selflessly. At Spartans Advisors, it feels more like family than colleagues. We learn, encourage and grow together. We work hard and play just as hard. Even as we grow in numbers, we leave no man behind at all cost.",
    credentials: ['Financial Services Consultant', '7 Years Experience'],
    rating: 5.0,
    clients: 150,
    image: '/advisors/yvonne.jpg',
    quote: '"Creating the life you want is only and always up to you. Go out there and hunt it."',
    email: 'yvonnelim@aia.com.sg',
    phone: '+65 8139 3410',
    whatsapp: 'https://api.whatsapp.com/send?phone=6581393410',
  },
  {
    slug: 'assuredbyalicia',
    name: 'Alicia Pe',
    title: 'Premier Consultant',
    specialty: 'Holistic Financial Planning for All Life Stages',
    bio: "I always wanted to be a doctor when I was a kid. Doctors save lives, are intelligent, and willing to heal the sick. But my less-than-ideal science grades disagreed. Where I excelled in were numbers and equations, and my grades in math, accounting and business paved my way as an auditor. I was unsettled. I always wanted to help people, so I decided to use my expertise to do that. I decided I wanted to be like a financial doctor instead — assess people's financial situation and come up with solutions that will help them. All patients are different, even patients with the same illness do not require the same treatment all the time. There are many factors to consider like the patient's age, pre-existing illnesses, allergies, etc. Similarly, everyone has different financial abilities, needs and priorities. It is my job to consider all of these factors before coming up with a solution for my patients. I believe that everyone needs professional financial planning. If they say they don't, it's because they haven't met the right person. I want to be that right person because I believe that financial planning should be possible for everyone from all walks of life.",
    credentials: ['Premier Consultant', 'AIA'],
    rating: 5.0,
    clients: 160,
    image: '/advisors/alicia.jpg',
    quote: '"If you cannot do great things, do small things in a great way."',
    email: 'aliciape@aia.com.sg',
    phone: '+65 9758 4104',
    whatsapp: 'https://api.whatsapp.com/send?phone=6597584104',
  },
  {
    slug: 'assuredbychermayne',
    name: 'Chermayne Tng',
    title: 'Financial Services Manager',
    specialty: 'Team Leadership & Empowerment-Focused Financial Advisory',
    bio: "With seven years of experience in financial advisory, my journey has grown from serving individuals to leading Themisyra — a space where futures are built and leaders are shaped. Today, my role is not only to deliver sound financial guidance but to empower both my clients and my team to rise with confidence and clarity. At the core, I lead by serving. I am committed to listening deeply, offering thoughtful direction, and standing alongside those who entrust me with their goals. I believe leadership is a continuous journey, and I hold myself to the same standard of growth and excellence that I encourage in others. At Themisyra, we stand for courage, compassion, and empowerment. Together, we move forward, leading with heart, building with strength, and shaping futures that endure.",
    credentials: ['Financial Services Manager', '7 Years Experience'],
    rating: 5.0,
    clients: 140,
    image: '/advisors/chermayne.png',
    quote: '"Rise with courage. Lead with heart. Empower without limits."',
    email: 'chermayne@aia.com.sg',
  },
  {
    slug: 'assuredbyglenn',
    name: 'Glenn Tng',
    title: 'Financial Services Consultant',
    specialty: 'Client Financial Empowerment & Community Building',
    bio: "I chose to join Spartans Advisor because of my deep-rooted passion for the banking and financial sectors. While I've always been interested in business, it was my cousin's insights into her work that truly piqued my curiosity about potential career paths. After a compelling conversation with her director, I felt inspired to take the next step in my journey. I believe in the importance of self-growth and personal development. To thrive in any field, we must constantly seek to improve ourselves. At Spartans, I find a strong alignment with this philosophy. Our systematic and robust structure not only empowers us to serve our clients effectively but also reinforces our commitment to a greater purpose. Being part of Spartans has provided me with a sense of belonging and fulfillment. My goal is to help clients reach their financial aspirations, even if that means they decide not to purchase from us. For me, it's about creating a supportive community where we prioritize value addition and sound financial planning.",
    credentials: ['Financial Services Consultant', 'AIA'],
    rating: 5.0,
    clients: 80,
    image: '/advisors/glenn.jpg',
    quote: '"Making money is art and working is art and good business is the best art."',
    email: 'Tngweihengglenn@aia.com.sg',
    phone: '+65 9477 0170',
    whatsapp: 'https://api.whatsapp.com/send?phone=6594770170',
  },
  {
    slug: 'assuredbyjanet',
    name: 'Janet Lim',
    title: 'Financial Services Consultant',
    specialty: 'Life-Stage Financial Planning & Trust-Based Advisory',
    bio: "When I first graduated, I didn't start my career thinking I would end up in financial services, but along the way, I realised what truly mattered to me: helping people make sense of important decisions, and doing work that genuinely improves their lives. Before this, I spent time as a cabin crew and then in a global bank. Those experiences taught me two things that still shape how I work today — the value of listening, and the importance of building trust with people from all walks of life. While I performed well in structured environments, I found myself wanting more meaningful conversations and deeper client relationships. That search eventually led me to AIA and the SPARTANS culture — a team of young, driven individuals who believe financial planning should be long-term, personal, and life-stage focused. I'm in this profession for the long run. I'm a strong believer that financial clarity brings peace of mind, and that everyone deserves to feel confident and informed about their financial choices. My goal is simple: to be a trusted advisor clients can rely on over time — someone they feel comfortable speaking with, asking questions, and making informed decisions together.",
    credentials: ['Financial Services Consultant', 'AIA'],
    rating: 5.0,
    clients: 120,
    image: '/advisors/janet.jpg',
    quote: '"What the mind of man can conceive and believe, it can achieve."',
    email: 'janetlim@aia.com.sg',
    phone: '+65 9109 5013',
    whatsapp: 'https://api.whatsapp.com/send?phone=6591095013',
  },
  {
    slug: 'assuredbylucas',
    name: 'Lucas Ng',
    title: 'Financial Services Consultant',
    specialty: 'Family Protection & Long-Term Wealth Planning',
    bio: "Everything meaningful starts with someone who truly cares. When I first heard about this industry, I had the same impression many people do — financial advisors often get a reputation for being focused on selling, meeting targets, and moving on. Getting to know Spartans Advisors completely shifted how I saw this industry. The community they have built and the way they genuinely prioritize adding value to people's lives showed me that financial planning can be so much more than transactions. It's about understanding people, listening closely, and guiding them in ways that truly matter. My family's own experience with insurance during tough times also reminded me how important proper planning can be. When cancer struck in our household, having coverage didn't just help with the bills — it gave us financial breathing room to focus on what truly mattered. My dad has always been someone who believes in planning ahead, and because of that, he was able to protect and grow what we had as a family. That kind of stability and assurance is something I want to help others achieve as well. At the heart of it, what drives me is simple: I want to bring real value to the people I meet, to make their lives a little more secure and their future a little brighter.",
    credentials: ['Financial Services Consultant', 'AIA'],
    rating: 5.0,
    clients: 70,
    image: '/advisors/lucas.jpg',
    quote: '"Someone\'s sitting in the shade today because someone planted a tree a long time ago." — Warren Buffett',
    email: 'lucasnzd@aia.com.sg',
    phone: '+65 8186 1314',
    whatsapp: 'https://api.whatsapp.com/send?phone=6581861314',
  },
  {
    slug: 'assuredbymatthias',
    name: 'Matthias Sim',
    title: 'Financial Services Consultant',
    specialty: 'Financial Literacy & Wealth Management',
    bio: "In a world that often feels like it's constantly moving at a rapid pace, we often neglect the people around us — especially in a corporate setting when we are constantly climbing the corporate ladder. I have always wanted a career that I could take charge of my own schedule while still doing something meaningful. I am a strong believer in advocating financial literacy to as many people as possible, especially after my family went through some very rough situations due to poor financial management. With proper financial management in place, I am sure that one can navigate the complexities of life with greater ease and confidence. Everyone at Spartans Advisors is on a shared journey towards collective success. We are committed to achieving our goals together, providing constant support to one another. The camaraderie among the team creates a supportive environment where everyone feels valued and appreciated, which gave me the confidence in being in Spartans.",
    credentials: ['Financial Services Consultant', 'AIA'],
    rating: 5.0,
    clients: 65,
    image: '/advisors/matthias.webp',
    quote: '"Let\'s embark on this journey with the enthusiasm of a dog chasing its tail, but with a bit more direction."',
    email: 'matthiasssw@aia.com.sg',
    phone: '+65 9235 5849',
    whatsapp: 'https://api.whatsapp.com/send?phone=6592355849',
  },
  {
    slug: 'assuredbyryan',
    name: 'Ryan Tan Li Wei',
    title: 'Financial Services Consultant',
    specialty: 'Protection Planning & Long-Term Financial Discipline',
    bio: "I was diagnosed with non-Hodgkin's lymphoma at 3 years old. Growing up, I never knew why I spent those days in the hospital or why I had to take the meds that I did. My parents sheltered me from the truth of my condition until they felt it was necessary that I knew. My family's finances took a toll. With barely any financial planning done, my family was not able to get adequate coverage for my condition. They had to make sacrifices to get by and it was a really difficult period for them. Over the years, I have looked forward to repaying what my family has done for me, and I believe it is every child's aspiration to provide for their parents so that they could retire. Unfortunately, I was not able to do this for my father, who worked tirelessly as a Grab driver till his unexpected death in 2022. I realised later that my parents' lives would have turned out very differently with a financial plan set in place. Today, I strive to fit the position that would have benefited my family all those years ago. My mother tells me that financial planning is a luxury for those with disposable income. But even fruit is considered a luxury to those that have never practised farming. It takes discipline to prioritise long-term gratification over the short-term. There is nothing more fulfilling than to provide for others, what I was not able to have myself.",
    credentials: ['Financial Services Consultant', 'AIA'],
    rating: 5.0,
    clients: 75,
    image: '/advisors/ryan.webp',
    quote: '"Financial planning is a lifelong process, and like all products of discipline, it is for a greater good."',
    email: 'ryantanliwei@aia.com.sg',
    phone: '+65 8499 1038',
    whatsapp: 'https://api.whatsapp.com/send?phone=6584991038',
  },
  {
    slug: 'assuredbyshearn',
    name: 'Lim Shearn Chong',
    title: 'Financial Services Manager',
    specialty: 'Sound Financial Planning & Retirement Preparation',
    bio: "Coming from a middle class family and falling into the slums due to unforeseen circumstances was a painful and life-changing experience for me when I was still a student in 2013. I made the decision to join this industry because I wanted to make a difference — I wanted to prevent my friends and people around me from going through the same situation as I had. Over the final year in university, I had realised the importance in sound financial planning, which can prevent unforeseen financial difficulties in life. Since then, I believe in the knowledge of sound financial planning and proper allocation of resources to prepare for the foreseeable future and ultimately, our own retirement. Being in this industry for almost 5 years, Spartans Advisors has groomed me into the financial consultant that I am today, holding the Premier title to my name. This career is never a sprint, it is a marathon. It is challenging yet fulfilling.",
    credentials: ['Financial Services Manager', 'Premier'],
    rating: 5.0,
    clients: 130,
    image: '/advisors/shearn.jpg',
    quote: '"Plan Your Work And Work Your Plan."',
    email: 'shearn@aia.com.sg',
    phone: '+65 9009 8940',
    whatsapp: 'https://api.whatsapp.com/send?phone=6590098940',
  },
  {
    slug: 'assuredbystacey',
    name: 'Stacey Teo',
    title: 'Financial Services Consultant',
    specialty: 'Client-Centred Financial Planning & Personal Development',
    bio: "Before embarking on my finance career, I spent years in the marketing industry. However, as time passed, I began to feel trapped in the confines of a 9-to-5 job. This dissatisfaction led me to transition into finance, believing it would grant me the financial freedom I sought. Yet, as I acquired more clients and began handling claims, I realized the true significance of my role. A pivotal moment came on my birthday when I received a claim while I was overseas. In that moment, I found myself more concerned for my client than I was for myself — highlighting the importance of what I do. I am a firm believer in self-growth and personal development. Being part of SPARTANS ADVISORS has provided me with a solid structure that empowers me to add real value for my clients. The guidance we receive is akin to parental support, ensuring that we are well taken care of as we navigate our careers. My ultimate goal is to help my clients enjoy every moment of their lives without the burden of financial worries.",
    credentials: ['Financial Services Consultant', 'AIA'],
    rating: 5.0,
    clients: 90,
    image: '/advisors/stacey.jpg',
    quote: '"We don\'t have to be smarter than the rest. We have to be more disciplined than the rest."',
    email: 'staceyteo@aia.com.sg',
    phone: '+65 9073 5281',
    whatsapp: 'https://api.whatsapp.com/send?phone=6590735281',
  },
  {
    slug: 'assuredbysijun',
    name: 'Lai Sijun',
    title: 'Financial Services Consultant',
    specialty: 'Wealth Protection & Risk Management',
    bio: "I am a people's person, driven by a sincere desire to help others. From personal coaching to aiding in their action plans, I aim to further assist people in financial growth and wealth protection. I believe in the protection of wealth and the management of the implications of health issues. Being part of this team means truly believing in protecting people's lives, investing in, and growing wealth. It's about being energetically involved, becoming a trusted advisor, and a mentor others can look up to. Spartans Advisors signify a rebirth and a fresh start in my life. It represents a commitment to advising on personal wealth and health growth, supported by a culture of excellence and strong leadership. I aim to help my clients achieve personal growth in wealth while ensuring protection and effective risk management. I invite you to join me on this financial planning journey, complemented by life coaching, to achieve your financial goals and secure your future.",
    credentials: ['Financial Services Consultant', 'AIA'],
    rating: 5.0,
    clients: 85,
    image: '/advisors/sijun.jpg',
    quote: '"Believe and you shall receive."',
    email: 'sijun@aia.com.sg',
    phone: '+65 9126 5170',
    whatsapp: 'https://api.whatsapp.com/send?phone=6591265170',
  },
  {
    slug: 'assuredbyvenice',
    name: 'Venice Tan',
    title: 'Financial Services Consultant',
    specialty: 'Relationship-Based Financial Planning',
    bio: "I've always been a people person. I love conversations, hearing stories, and understanding what drives someone. I knew I didn't want a routine job; I wanted something with purpose, connection, and impact. That's what led me to financial planning. More than just charts or strategies, this career gives me the chance to truly help people — to teach, to guide, and to bring clarity to something that often feels confusing or overwhelming. Being part of Spartans Advisors has made all the difference. It's more than a team, it's a family. We support each other, celebrate wins together, and grow through our setbacks. The culture here is built on trust, care, and showing up — not just for each other, but for our clients. I believe financial planning should feel human. I want to be there for your big milestones, but also in the quiet in-betweens: when you need clarity, support, or even just someone to talk to. This journey isn't just about money — it's about life. And I'll walk it with you.",
    credentials: ['Financial Services Consultant', 'AIA'],
    rating: 5.0,
    clients: 60,
    image: '/advisors/venice.jpg',
    quote: '"The best advice comes from our strongest ties."',
    email: 'venice@aia.com.sg',
    phone: '+65 9883 5832',
    whatsapp: 'https://api.whatsapp.com/send?phone=6598835832',
  },
  {
    slug: 'assuredbyweihao',
    name: 'Eng Wei Hao',
    title: 'Premier Consultant',
    specialty: 'Holistic Financial Planning & Long-Term Client Relationships',
    bio: "As a financial service consultant, I can work closely with clients over long periods of time. This provides an opportunity to build lasting relationships based on trust and mutual respect. I strongly believe in the power of personal development and holistic well-being. The way we grow, adapt, and improve is a form of wealth that goes beyond material possessions, offering a more lasting and meaningful pursuit. Holistic well-being takes a comprehensive approach to health, considering the mind, body, and spirit as interconnected elements, rather than focusing on any one aspect in isolation. Spartans Advisors is like a family to me, offering both support and accountability. It embodies a strong commitment to delivering exceptional service, expert financial advice, and always striving for the best outcomes for our clients. I aim to not only be a trusted financial consultant but also a pivotal figure in my clients' lives, guiding them through complex decisions and celebrating their financial achievements along the way.",
    credentials: ['Premier Consultant', 'AIA'],
    rating: 5.0,
    clients: 110,
    image: '/advisors/weihao.jpg',
    quote: '"What you achieve may fade, but who you become will echo throughout your life."',
  },
  {
    slug: 'assuredbyxxia',
    name: 'Xxia Yip',
    title: 'Financial Services Consultant',
    specialty: 'Empathetic Financial Guidance & Wealth Protection',
    bio: "As someone who values genuine connections with people from all walks of life, I'm always looking for meaningful ways to bring value into their lives. To me, it has never been just about the policies; it has always been about the people behind them. My background in Social Work allows me to approach this role with empathy, patience, and sincerity. It gives me the lens to see clients not as numbers, but as individuals with hopes, worries, and dreams. Being able to guide them through important decisions and help them feel more secure aligns perfectly with the kind of impact I want to make. Spartans also played a big part in my decision — out of the many districts in the industry, it has to be them, or no one else. The culture here is genuine, supportive, and real — a place where people truly want to see each other grow. I want to be the person that clients trust, someone they feel comfortable with, someone who listens, understands, and provides genuine guidance. I want to show that financial consultants can lead with heart, integrity, and sincerity.",
    credentials: ['Financial Services Consultant', 'Social Work Background'],
    rating: 5.0,
    clients: 55,
    image: '/advisors/xxia.jpg',
    quote: '"A life spent helping others is a life that truly matters."',
    email: 'xxiayip@aia.com.sg',
    phone: '+65 9111 0008',
    whatsapp: 'https://api.whatsapp.com/send?phone=6591110008',
  },
]

export function getAdvisorBySlug(slug: string): Advisor | undefined {
  return advisors.find((a) => a.slug === slug)
}
